baseURL = "https://example.com"
languageCode = "en-us"
title = "Michael DeCrescenzo"
theme = "hugo-theme-cactus"
copyright = "" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

# blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Public Research"
url = "/research"
weight = 4

# [[menu.main]]
# name = "Code Projects"
# url = "/projects"
# weight = 5

[[menu.main]]
name = "Teaching Resources"
url = "/teaching"
weight = 6

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  mathjax = true
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "I am a statistical researcher working in quantitative/high-frequency finance. This site contains some info about me, some notes about my work, and blog posts about stats and statistical programming."

  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 2 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/mikedecr"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/mikedecr"
  # [[params.social]]
  #   name = "email"
  #   link = "example@example.com"  # no need for "mailto:" in the head
